steps:
  - name: jekyll/jekyll:3.8
    args: ["jekyll", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./_site", "gs://biddlyboops-catherineritchie-co-uk"]
